# Generated by Django 2.2.1 on 2019-06-03 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20190603_1304'),
    ]

    operations = [
    ]
